[deploy]
bucket = 'cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:715606626438:certificate/3c49f37a-a67c-43a4-adb0-53e38d8892dd'
NetworkingStack = 'CrdNet'